baseURL: https://dhruv-thoughts.netlify.app/
languageCode: en-us
title: Portfolio Website for Dhruv Ghurburrun
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
     #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hello. My name is Dhruv. Welcome to my blog. 
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Balcombe Street
        title: 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: dghurburrun.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- #icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/DhruvM.G
      #- #icon: fa-instagram
        #label: Instagram
        #url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/dhruvMg1804
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/dhruv-ghurburrun-aa021a140/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      #- name: Generic Blog
        #url: blogs/ipsum
      #- name: Elements
        #url: elements.html
    menu: Menu
   # subtitle: By HTML5 Up
    title: Home
  tiles:
    enable: yes
    showcase:
      - image: Mauritius.jpg
        subtitle: Home
        title: Mauritius
        url: blogs/risk_return
      - image: London.jpeg
        subtitle: The City
        title: London
        url: blogs/risk_return3
      - image: library.jpg
        subtitle: Inspiration
        title: Books
        url: blogs/risk_return4
      - image: movies.jpg
        subtitle: Pleasure 
        title: Movies
        url: blogs/risk_return2
      - image: Food.jpg
        subtitle: Life
        title: Food
        url: blogs/risk_return5
      - image: Road.jpg
        subtitle: What's next?
        title: My Future 
        url: blogs/risk_return6
  two:
    buttonText: Get Started
    enable: yes
    subtitle: " My motto in life is be patient for the goals you seek and be happy in the meantime. Enjoy the journey as much as possible. 
    While I try to make it as an investment specialist in the City of London, I am trying to enjoy the little things that I encounter on my way. 
    It is not always easy when you are very ambitious and you encounter failure at every corner but I know that there is light at the end of the tunnel
    and I just need to walk the path down there. In the mean time, I'm trying to fill this website with my life and trying to inspire people with this philosophy.
      "
    title: What makes me tick?
    url: blogs
  